
[general]
	y_location = 1.0
	overlay_opacity = 0.0
	splits_scale = 1.0
	x_location = 1.0
	kuudra_splits = true

[color]

	[color.general]
		split_time = true

	[color.splits_color]
		build_color = 11
		skip_color = 11
		p4_color = 11
		overall_color = 11
		stun_color = 11
		dps_color = 11
		supply_color = 11
		eaten_color = 11

